// Copyright 2026 Stephan Schlöpke
// SPDX-License-Identifier: Apache-2.0

@_spi(Compiler) import GameEventScriptRuntime

extension GesCompiler {
    static let assemblyInstructions: [String: (Op, String, [Int])] = [
        "Nop": (.nop, "", []),
        "RandomTake": (.randomTake, "wrr", [0, 1, 2]),
        "RandomTakeFloat": (.randomTakeFloat, "wrr", [0, 1, 2]),
        "LoadInteger": (.loadInteger, "wi", [0, 7]),
        "LoadFloat": (.loadFloat, "wf", [0, 7]),
        "Jump": (.jump, "l", [2]),
        "JumpIfTrue": (.jumpIfTrue, "rl", [1, 2]),
        "JumpIfFalse": (.jumpIfFalse, "rl", [1, 2]),
        "JumpIfNotTrue": (.jumpIfNotTrue, "rl", [1, 2]),
        "JumpIfNothing": (.jumpIfNothing, "rl", [1, 2]),
        "CastCustom": (.castCustom, "wrt", [0, 1, 2]),
        "ParseLiteral": (.parseLiteral, "wr", [0, 1]),
        "CastNumeric": (.castNumeric, "wr", [0, 1]),
        "CheckCustomType": (.checkCustomType, "wrt", [0, 1, 2]),
        "CheckNumeric": (.checkNumeric, "wr", [0, 1]),
        "CheckInteger": (.checkInteger, "wr", [0, 1]),
        "CheckFractional": (.checkFractional, "wr", [0, 1]),
        "Move": (.move, "wr", [0, 1]),
        "MemberAccess": (.memberAccess, "wtr", [0, 1, 2]),
        "IndexAccess": (.indexAccess, "wur", [0, 1, 2]),
        "PropertyAccess": (.propertyAccess, "wrr", [0, 1, 2]),
        "LoadNothing": (.loadNothing, "w", [0]),
        "LoadTrue": (.loadTrue, "w", [0]),
        "LoadFalse": (.loadFalse, "w", [0]),
        "LoadPercentage": (.loadPercentage, "wf", [0, 7]),
        "LoadText": (.loadText, "wt", [0, 1]),
        "LoadTag": (.loadTag, "wt", [0, 1]),
        "CreateDice": (.createDice, "wss", [0, 1, 2]),
        "CreateRange": (.createRange, "wrr", [0, 1, 2]),
        "CreateRangeWithStep": (.createRangeWithStep, "wrrr", [0, 1, 2, 3]),
        "CreateRangeIterator": (.createRangeIterator, "wrr", [0, 1, 2]),
        "CreateRangeIteratorWithStep": (.createRangeIteratorWithStep, "wrrr", [0, 1, 2, 3]),
        "CreateRangeIteratorShort": (.createRangeIteratorShort, "wsss", [0, 1, 2, 3]),
        "HasValue": (.hasValue, "wr", [0, 1]),
        "IsEmpty": (.isEmpty, "wr", [0, 1]),
        "Default": (.default, "wrr", [0, 1, 2]),
        "Or": (.or, "wrr", [0, 1, 2]),
        "And": (.and, "wrr", [0, 1, 2]),
        "Xor": (.xor, "wrr", [0, 1, 2]),
        "Implies": (.implies, "wrr", [0, 1, 2]),
        "Not": (.not, "wr", [0, 1]),
        "Equal": (.equal, "wrr", [0, 1, 2]),
        "NotEqual": (.notEqual, "wrr", [0, 1, 2]),
        "Less": (.less, "wrr", [0, 1, 2]),
        "Greater": (.greater, "wrr", [0, 1, 2]),
        "LessOrEqual": (.lessOrEqual, "wrr", [0, 1, 2]),
        "GreaterOrEqual": (.greaterOrEqual, "wrr", [0, 1, 2]),
        "Add": (.add, "wrr", [0, 1, 2]),
        "Subtract": (.subtract, "wrr", [0, 1, 2]),
        "Cartesian": (.cartesian, "wrr", [0, 1, 2]),
        "Multiply": (.multiply, "wrr", [0, 1, 2]),
        "Divide": (.divide, "wrr", [0, 1, 2]),
        "Power": (.power, "wrr", [0, 1, 2]),
        "IntegerDivide": (.integerDivide, "wrr", [0, 1, 2]),
        "Modulo": (.modulo, "wrr", [0, 1, 2]),
        "Remainder": (.remainder, "wrr", [0, 1, 2]),
        "Min": (.min, "wrr", [0, 1, 2]),
        "Max": (.max, "wrr", [0, 1, 2]),
        "Negate": (.negate, "wr", [0, 1]),
        "Abs": (.abs, "wr", [0, 1]),
        "LogN": (.logN, "wr", [0, 1]),
        "Chance": (.chance, "wr", [0, 1]),
        "Exp": (.exp, "wr", [0, 1]),
        "Floor": (.floor, "wr", [0, 1]),
        "Ceil": (.ceil, "wr", [0, 1]),
        "Truncate": (.truncate, "wr", [0, 1]),
        "RoundHalfEven": (.roundHalfEven, "wr", [0, 1]),
        "RoundHalfUp": (.roundHalfUp, "wr", [0, 1]),
        "RoundHalfDown": (.roundHalfDown, "wr", [0, 1]),
        "DegreeToRadians": (.degreeToRadians, "wr", [0, 1]),
        "DegreeFromRadians": (.degreeFromRadians, "wr", [0, 1]),
        "WrapDegree": (.wrapDegree, "wr", [0, 1]),
        "Sin": (.sin, "wr", [0, 1]),
        "Cos": (.cos, "wr", [0, 1]),
        "Tan": (.tan, "wr", [0, 1]),
        "Asin": (.asin, "wr", [0, 1]),
        "Acos": (.acos, "wr", [0, 1]),
        "Atan": (.atan, "wr", [0, 1]),
        "Atan2": (.atan2, "wrr", [0, 1, 2]),
        "Hypot2D": (.hypot2D, "wrr", [0, 1, 2]),
        "Hypot3D": (.hypot3D, "wrrr", [0, 1, 2, 3]),
        "Distance": (.distance, "wrr", [0, 1, 2]),
        "Distance2D": (.distance2D, "wrrrr", [0, 1, 2, 3, 4]),
        "Distance3D": (.distance3D, "wrrrrrr", [0, 1, 2, 3, 4, 5, 6]),
        "DistanceSquared": (.distanceSquared, "wrr", [0, 1, 2]),
        "DistanceSquared2D": (.distanceSquared2D, "wrrrr", [0, 1, 2, 3, 4]),
        "DistanceSquared3D": (.distanceSquared3D, "wrrrrrr", [0, 1, 2, 3, 4, 5, 6]),
        "LengthSquared": (.lengthSquared, "wr", [0, 1]),
        "LengthSquared2D": (.lengthSquared2D, "wrr", [0, 1, 2]),
        "LengthSquared3D": (.lengthSquared3D, "wrrr", [0, 1, 2, 3]),
        "Normalize": (.normalize, "wr", [0, 1]),
        "Normalize2D": (.normalize2D, "wrr", [0, 1, 2]),
        "Normalize3D": (.normalize3D, "wrrr", [0, 1, 2, 3]),
        "Dot": (.dot, "wrr", [0, 1, 2]),
        "Dot2D": (.dot2D, "wrrrr", [0, 1, 2, 3, 4]),
        "Dot3D": (.dot3D, "wrrrrrr", [0, 1, 2, 3, 4, 5, 6]),
        "Cross": (.cross, "wrr", [0, 1, 2]),
        "Cross2D": (.cross2D, "wrrrr", [0, 1, 2, 3, 4]),
        "Cross3D": (.cross3D, "wrrrrrr", [0, 1, 2, 3, 4, 5, 6]),
        "AngleBetween": (.angleBetween, "wrr", [0, 1, 2]),
        "AngleBetween2D": (.angleBetween2D, "wrrrr", [0, 1, 2, 3, 4]),
        "AngleBetween3D": (.angleBetween3D, "wrrrrrr", [0, 1, 2, 3, 4, 5, 6]),
        "Clamp": (.clamp, "wrrr", [0, 1, 2, 3]),
        "Term": (.term, "wrr", [0, 1, 2]),
        "TakeFirst": (.takeFirst, "wrs", [0, 1, 2]),
        "DropFirst": (.dropFirst, "wrs", [0, 1, 2]),
        "TakeLast": (.takeLast, "wrs", [0, 1, 2]),
        "DropLast": (.dropLast, "wrs", [0, 1, 2]),
        "TakeHighest": (.takeHighest, "wrs", [0, 1, 2]),
        "TakeLowest": (.takeLowest, "wrs", [0, 1, 2]),
        "DropHighest": (.dropHighest, "wrs", [0, 1, 2]),
        "DropLowest": (.dropLowest, "wrs", [0, 1, 2]),
        "OneRandom": (.oneRandom, "wr", [0, 1]),
        "TakeRandom": (.takeRandom, "wrs", [0, 1, 2]),
        "OneWeighted": (.oneWeighted, "wrr", [0, 1, 2]),
        "TakeWeighted": (.takeWeighted, "wrrs", [0, 1, 3, 2]),
        "Count": (.count, "wr", [0, 1]),
        "StartsWith": (.startsWith, "wrr", [0, 1, 2]),
        "EndsWith": (.endsWith, "wrr", [0, 1, 2]),
        "Contains": (.contains, "wrr", [0, 1, 2]),
        "ContainsAny": (.containsAny, "wrr", [0, 1, 2]),
        "ContainsAll": (.containsAll, "wrr", [0, 1, 2]),
        "HasAny": (.hasAny, "wr", [0, 1]),
        "HasAll": (.hasAll, "wr", [0, 1]),
        "ContainsValue": (.containsValue, "wrr", [0, 1, 2]),
        "Union": (.union, "wrr", [0, 1, 2]),
        "Intersect": (.intersect, "wrr", [0, 1, 2]),
        "Zip": (.zip, "wrr", [0, 1, 2]),
        "KeysOfMap": (.keysOfMap, "wr", [0, 1]),
        "ValuesOfMap": (.valuesOfMap, "wr", [0, 1]),
        "EntriesOfMap": (.entriesOfMap, "wr", [0, 1]),
        "First": (.first, "wr", [0, 1]),
        "Last": (.last, "wr", [0, 1]),
        "Single": (.single, "wr", [0, 1]),
        "IteratorCreate": (.iteratorCreate, "wr", [0, 1]),
        "IteratorCreateOrJump": (.iteratorCreateOrJump, "wrl", [0, 1, 2]),
        "IteratorNext": (.iteratorNext, "wrl", [0, 1, 2]),
        "IteratorClose": (.iteratorClose, "r", [1]),
        "Distinct": (.distinct, "wr", [0, 1]),
        "SortAscending": (.sortAscending, "wr", [0, 1]),
        "SortDescending": (.sortDescending, "wr", [0, 1]),
        "Reverse": (.reverse, "wr", [0, 1]),
        "Shuffle": (.shuffle, "wr", [0, 1]),
        "ListBuilderCreate": (.listBuilderCreate, "w", [0]),
        "ListBuilderAdd": (.listBuilderAdd, "rr", [1, 2]),
        "ListBuilderFinish": (.listBuilderFinish, "wr", [0, 1]),
        "MapBuilderCreate": (.mapBuilderCreate, "w", [0]),
        "MapBuilderAdd": (.mapBuilderAdd, "rrr", [1, 2, 3]),
        "MapBuilderFinish": (.mapBuilderFinish, "wr", [0, 1]),
        "DistinctBuilderCreate": (.distinctBuilderCreate, "w", [0]),
        "DistinctBuilderAdd": (.distinctBuilderAdd, "rrr", [1, 2, 3]),
        "DistinctBuilderFinish": (.distinctBuilderFinish, "wr", [0, 1]),
        "GroupBuilderCreate": (.groupBuilderCreate, "w", [0]),
        "GroupBuilderAdd": (.groupBuilderAdd, "rrr", [1, 2, 3]),
        "GroupBuilderFinish": (.groupBuilderFinish, "wr", [0, 1]),
        "OrderBuilderCreate": (.orderBuilderCreate, "w", [0]),
        "OrderBuilderAdd": (.orderBuilderAdd, "rrr", [1, 2, 3]),
        "OrderBuilderFinishAscending": (.orderBuilderFinishAscending, "wr", [0, 1]),
        "OrderBuilderFinishDescending": (.orderBuilderFinishDescending, "wr", [0, 1]),
    ]
}
