<!-- Copyright 2026 Stephan Schlöpke -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<Project>
    <Import Project="../../../../Directory.Build.props" />
    <PropertyGroup>
        <BaseOutputPath>$(MSBuildThisFileDirectory)../../../../artifacts/csharp/tool/bin/</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../../../../artifacts/csharp/tool/obj/</BaseIntermediateOutputPath>
    </PropertyGroup>
</Project>
