#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.CompilerServices;
using Beamable.Api.Autogenerated.Models;
using StepH.GameEventScript.Api;
using StepH.GameEventScript.Types;
using static StepH.GameEventScript.Api.GameEventScriptBinaryBindTable;

namespace StepH.GameEventScript.BytecodeExecutor;

[SuppressMessage("ReSharper", "MemberCanBePrivate.Global")]
public struct VmState
{
    public enum StateValue
    {
        Initialized,
        Ready,
        Running,
        Halted,
        Error
    }

    public struct CallFrame
    {
        public ushort InstructionPointer;
        public ushort? ResultRegisterIndex;
        public ushort RegisterFrameStart;
        public ushort RegisterFrameLength;
    }

    public GameEventScriptBinary Binary { get; init; }

    public StateValue State { get; internal set; }

    public ushort InstructionPointer { get; private set; } = 0;
    public ushort CallStackPointer { get; private set; } = 0;
    public CallFrame[] CallStack { get; init; }

    public VmValue[] RegisterSlots { get; init; }

    public ushort RandomGeneratorsPointer { get; private set; } = 0;
    public GameEventScriptRandomGenerator[] RandomGenerators { get; init; }
    public GameEventScriptRandomGenerator RandomGenerator { get; private set; }

    public ushort RegisterFrameStart = 0;
    public ushort RegisterFrameLength = 0;
    public ushort StagedArgumentCount = 0;
    
    public string? ErrorMessage { get; private set; } = null;

    public Dictionary<string, GameEventScriptBinaryBindEntry> InboundMessageHandlers { get; init; }
    public List<GameEventScriptMessageSignature> OutboundMessageSignatures { get; init; }

    public readonly ushort CodeSegmentSize; 

    public VmState(GameEventScriptBinary binary, ushort registerSize, ushort stackSize)
    {
        Binary = binary;
        CodeSegmentSize = checked((ushort)binary.InstructionTable.Length);
        InstructionPointer = 0;
        CallStackPointer = 0;
        CallStack = new CallFrame[stackSize];
        RegisterSlots = new VmValue[registerSize];
        RandomGenerators = new GameEventScriptRandomGenerator[16];
        for (var i = 0; i < RegisterSlots.Length; i++)
        {
            RegisterSlots[i].SetNothing();
        }
        InboundMessageHandlers = binary.BindTable.Entries.Where(x => x.Kind == GameEventScriptBinaryBindKind.MessageHandler).ToDictionary(
            bind => GameEventScriptMessageSignature.CreateSignatureId(binary.TextConstantTable.Resolve(bind.Name), bind.ArgumentNames.Select(binary.TextConstantTable.Resolve)),
            x => x);
    }

    public bool PrepareMessage(GameEventScriptMessage message, GameEventScriptContext context)
    {
        if (State != StateValue.Initialized) return RaiseError("Handler can only be loaded when the VM is initialized.");
        var signatureId = message.SignatureId;
        if (!InboundMessageHandlers.TryGetValue(signatureId, out var bind)) return RaiseError($"No handler found for message '{signatureId}'.");
        if (bind.Kind != GameEventScriptBinaryBindKind.MessageHandler) return RaiseError($"Message '{signatureId}' is not a handler.");
        if (bind.ArgumentNames.Count != message.Arguments.Count) return RaiseError($"Message '{signatureId}' has the wrong number of arguments.");
        var arguments = message.Arguments;
        if (arguments.Count > RegisterSlots.Length) return RaiseError($"Message '{signatureId}' has too many arguments for the VM register frame.");
        if (bind.EntryAddress >= CodeSegmentSize) return RaiseError($"Message '{signatureId}' has an invalid entry address.");
        InstructionPointer = bind.EntryAddress;
        RegisterFrameStart = 0;
        RegisterFrameLength = (ushort)arguments.Count;
        for (var i = 0; i < RegisterFrameLength; i++) 
        {
            RegisterSlots[i].BindArguments(arguments[i]);
        }
        RandomGenerator = context.Random;
        RandomGeneratorsPointer = 0;
        State = StateValue.Ready;
        return true;
    }

    public bool PushRandom(GameEventScriptRandomGenerator randomGenerator)
    {
        if (RandomGeneratorsPointer >= RandomGenerators.Length) return RaiseError("Random generator stack overflow");
        RandomGenerators[RandomGeneratorsPointer++] = randomGenerator;
        RandomGenerator = randomGenerator;
        return true;
    }
    
    public bool PopRandom()
    {
        if (RandomGeneratorsPointer == 0) return RaiseError("Random generator stack underflow");
        RandomGenerator = RandomGenerators[--RandomGeneratorsPointer];
        return true;
    }
    
    public bool RaiseError(string message)
    {
        State = StateValue.Error;
        ErrorMessage = message;
        return false;
    }


    public void Reset()
    {
        InstructionPointer = 0;
        CallStackPointer = 0;
        State = StateValue.Initialized;
        RegisterFrameStart = 0;
        RegisterFrameLength = 0;
    }

    public void JumpAddress(ushort address)
    {
        InstructionPointer = address;
    }

    public bool CallAddress(ushort address, ushort? resultRegister = null)
    {
        if (CallStackPointer >= CallStack.Length) return RaiseError("Stack overflow");
        CallStack[CallStackPointer++] = new CallFrame
        {
            InstructionPointer = InstructionPointer,
            ResultRegisterIndex = resultRegister,
            RegisterFrameStart = RegisterFrameStart,
            RegisterFrameLength = RegisterFrameLength
        };
        InstructionPointer = address;
        RegisterFrameStart += RegisterFrameLength;
        RegisterFrameLength = StagedArgumentCount;
        StagedArgumentCount = 0;
        return RegisterFrameStart + RegisterFrameLength <= RegisterSlots.Length || RaiseError($"Register overflow");
    }

    public bool CallAddressFromRegister(ushort registerIndex, ushort? resultRegister = null)
    {
        if (CallStackPointer >= CallStack.Length) return RaiseError("Stack overflow");
        if (registerIndex >= RegisterFrameLength) return RaiseError($"Register overflow");
        var register = RegisterSlots[registerIndex + RegisterFrameStart];
        CallStack[CallStackPointer++] = new CallFrame
        {
            InstructionPointer = InstructionPointer,
            ResultRegisterIndex = resultRegister,
            RegisterFrameStart = RegisterFrameStart,
            RegisterFrameLength = RegisterFrameLength
        };
        if (register.CodePointerOrNothing == null)
        {
            return RaiseError($"Illegal call: register {registerIndex} is not a code pointer.");
        }
        InstructionPointer = register.CodePointerOrNothing ?? throw new InvalidOperationException();
        RegisterFrameStart += RegisterFrameLength;
        RegisterFrameLength = StagedArgumentCount;
        StagedArgumentCount = 0;
        return RegisterFrameStart + RegisterFrameLength <= RegisterSlots.Length || RaiseError($"Register overflow");
    }

    public void ReturnVoid()
    {
        if (CallStackPointer == 0)
        {
            State = StateValue.Halted;
            return;
        }

        var callFrame = CallStack[--CallStackPointer];
        InstructionPointer = callFrame.InstructionPointer;
        RegisterFrameStart = callFrame.RegisterFrameStart;
        RegisterFrameLength = callFrame.RegisterFrameLength;
        if (callFrame.ResultRegisterIndex.HasValue) RegisterSlots[callFrame.ResultRegisterIndex.Value + RegisterFrameStart].SetNothing();
    }

    public void ReturnValue(ushort registerIndex)
    {
        var result = RegisterSlots[registerIndex + RegisterFrameStart];
        var callFrame = CallStack[--CallStackPointer];
        InstructionPointer = callFrame.InstructionPointer;
        RegisterFrameStart = callFrame.RegisterFrameStart;
        RegisterFrameLength = callFrame.RegisterFrameLength;
        if (callFrame.ResultRegisterIndex.HasValue) RegisterSlots[callFrame.ResultRegisterIndex.Value + RegisterFrameStart] = result;
    }

    public GameEventScriptBytecodeInstruction FetchInstructionAndIncrementInstructionPointer()
    {
        return InstructionPointer >= CodeSegmentSize ? throw new OverflowException() : Binary.InstructionTable[InstructionPointer++];
    }

    public string FetchStringByPointer(ushort index)
    {
        return Binary.TextConstantTable.Resolve(index);
    }

    public ReadOnlySpan<ushort> FetchUInt16SliceTableByPointer(ushort index)
    {
        return Binary.Uint16ConstantTable.Resolve(index);
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AddLocalSlots(ushort slotCount)
    {
        var requiredTotalSlots = RegisterFrameStart + slotCount;
        if (requiredTotalSlots > RegisterSlots.Length)
        {
            // FIXME: Here we might want to let the register frame grow.
            RaiseError("Not enough slots in register frame.");
        }
        else
        {
            RegisterFrameLength += slotCount;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void RemoveLocalSlots(ushort slotCount)
    {
        if (RegisterFrameLength < slotCount)
        {
            // FIXME: Here we might want to let the register frame grow.
            RaiseError("Inconsistent register frame length. Cannot remove more slots than are available.");
        }
        else
        {
            RegisterFrameLength -= slotCount;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref VmValue AddStageSlot()
    {
        var stageRegisterIndex = RegisterFrameStart + RegisterFrameLength + StagedArgumentCount++;
        if (stageRegisterIndex >= RegisterSlots.Length) 
        {
            // FIXME: Here we might want to let the register frame grow.
            RaiseError("Cannot add more staged arguments than available register slots.");
        }
        return ref RegisterSlots[stageRegisterIndex];
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageRegister(ushort index)
    {
        AddStageSlot() = RegisterSlots[index + RegisterFrameStart];
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageNothing()
    {
        AddStageSlot().SetNothing();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageBoolean(bool value)
    {
        AddStageSlot().SetBoolean(value);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageInteger(long value, GameEventScriptBytecodeInstructionUnit unit)
    {
        AddStageSlot().SetInteger(value, unit);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageFloat(double value, GameEventScriptBytecodeInstructionUnit unit)
    {
        AddStageSlot().SetFloat(value, unit);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StagePercentage(double value)
    {
        AddStageSlot().SetPercentage(value);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageTextConstant(ushort constantIndex)
    {
        AddStageSlot().SetStringPointer(constantIndex);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void StageTagConstant(ushort constantIndex)
    {
        AddStageSlot().SetTagPointer(constantIndex);
    }
    
}