using System;
using static StepH.GameEventScript.Api.GameEventScriptOpcodePrinter.OperandPart;

namespace StepH.GameEventScript.Api;

// ReSharper disable InconsistentNaming
internal static class GameEventScriptOpcodePrinter
{
    internal enum OperandPart
    {
        TargetRegister,
        OutboundMessage,

        SourceRegister,
        LeftRegister,
        RightRegister,
        OperandRegister,
        ReturnRegister,
        MessageRegister,
        HandlerRegister,
        PropertyRegister,
        ObjectRegister,
        BuilderRegister,
        ItemRegister,
        KeyRegister,
        ValueRegister,
        ItemBindingRegister,
        AuxItemBindingRegister,
        WeightRegister,
        ConditionRegister,
        CollectionRegister,
        IteratorRegister,
        SourceIteratorRegister,
        SeriesRegister,
        IndexRegister,
        DefaultRegister,
        SeedRegister,
        NeedleRegister,
        FromRegister,
        ToRegister,
        StepRegister,
        MinimumRegister,
        MaximumRegister,
        AuxARegister,
        AuxBRegister,
        AuxCRegister,
        AuxDRegister,

        LocalRegisterDelta,
        DiceCount,
        DiceSideCount,
        ComponentCount,
        CountImmediate,
        IndexImmediate,
        FromImmediate,
        ToImmediate,
        StepImmediate,
        IntegerImmediate,
        FloatImmediate,
        Unit,

        JumpTarget,
        EntryTarget,
        CallableEntry,
        PredicateEntry,
        NextEntry,
        ProjectionEntry,
        KeyEntry,
        ValueEntry,
        FaceRegister,

        String,
        Text,
        Tag,
        MemberName,
        TypeKind,
        PatternKind,
        CustomTypeName,
        TypeName,

        MessageShapeList,
        StandardExtensionShapeList,
        ArgumentNameList,
        ArgumentRegisterList,
        ItemRegisterList,
        KeyNameList,
        ValueRegisterList,
        CaptureRegisterList,
        TagRegisterList,
        RecordReference,
        ExternalReference
    }

    internal static OperandPart[] PrintInstruction(GameEventScriptBytecodeInstruction instruction)
    {
        return instruction.OpCode switch
        {
            GameEventScriptBytecodeOpCode.Nop => [],
            GameEventScriptBytecodeOpCode.RegisterLocals => [LocalRegisterDelta],
            GameEventScriptBytecodeOpCode.Jump => [JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfTrue => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfFalse => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfNotTrue => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfNothing => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.Call => [TargetRegister, CallableEntry],
            GameEventScriptBytecodeOpCode.CallStandard => [TargetRegister, StandardExtensionShapeList, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.CallExternal => [TargetRegister, ExternalReference, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.ReturnVoid => [],
            GameEventScriptBytecodeOpCode.ReturnValue => [ReturnRegister],

            GameEventScriptBytecodeOpCode.EmitMessage => [OutboundMessage, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.EmitMessageWithTags => [OutboundMessage, ArgumentRegisterList, TagRegisterList],
            GameEventScriptBytecodeOpCode.EmitMessageValue => [MessageRegister],
            GameEventScriptBytecodeOpCode.EmitMessageValueWithTags => [MessageRegister, TagRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessage => [OutboundMessage, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessageWithTags => [OutboundMessage, ArgumentRegisterList, TagRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessageValue => [MessageRegister],
            GameEventScriptBytecodeOpCode.PublishMessageValueWithTags => [MessageRegister, TagRegisterList],

            GameEventScriptBytecodeOpCode.Cast => [TargetRegister, SourceRegister, TypeKind],
            GameEventScriptBytecodeOpCode.CastCustom => [TargetRegister, SourceRegister, CustomTypeName],
            GameEventScriptBytecodeOpCode.CastUnit => [TargetRegister, SourceRegister, Unit],
            GameEventScriptBytecodeOpCode.CastNumeric => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckType => [TargetRegister, SourceRegister, TypeKind],
            GameEventScriptBytecodeOpCode.CheckCustomType => [TargetRegister, SourceRegister, CustomTypeName],
            GameEventScriptBytecodeOpCode.CheckUnit => [TargetRegister, SourceRegister, Unit],
            GameEventScriptBytecodeOpCode.CheckNumeric => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckInteger => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckFractional => [TargetRegister, SourceRegister],

            GameEventScriptBytecodeOpCode.Move => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.MemberAccess => [TargetRegister, MemberName, ObjectRegister],
            GameEventScriptBytecodeOpCode.IndexAccess => [TargetRegister, IndexImmediate, ObjectRegister],
            GameEventScriptBytecodeOpCode.PropertyAccess => [TargetRegister, PropertyRegister, ObjectRegister],
            GameEventScriptBytecodeOpCode.BindHandler => [TargetRegister, HandlerRegister, ArgumentRegisterList],

            GameEventScriptBytecodeOpCode.LoadNothing => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadTrue => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadFalse => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadInteger => [TargetRegister, IntegerImmediate, Unit],
            GameEventScriptBytecodeOpCode.LoadFloat => [TargetRegister, FloatImmediate, Unit],
            GameEventScriptBytecodeOpCode.LoadPercentage => [TargetRegister, FloatImmediate],
            GameEventScriptBytecodeOpCode.LoadText => [TargetRegister, Text],
            GameEventScriptBytecodeOpCode.LoadTag => [TargetRegister, Tag],
            GameEventScriptBytecodeOpCode.LoadHandler => [TargetRegister, MessageShapeList],
            GameEventScriptBytecodeOpCode.LoadMessage => [TargetRegister, MessageShapeList, ArgumentRegisterList],

            GameEventScriptBytecodeOpCode.StageRegister => [SourceRegister],
            GameEventScriptBytecodeOpCode.StageNothing => [],
            GameEventScriptBytecodeOpCode.StageTrue => [],
            GameEventScriptBytecodeOpCode.StageFalse => [],
            GameEventScriptBytecodeOpCode.StageInteger => [IntegerImmediate, Unit],
            GameEventScriptBytecodeOpCode.StageFloat => [FloatImmediate, Unit],
            GameEventScriptBytecodeOpCode.StageText => [Text],
            GameEventScriptBytecodeOpCode.StageTag => [Tag],
            GameEventScriptBytecodeOpCode.StagePercentage => [FloatImmediate],

            GameEventScriptBytecodeOpCode.CreateDice => [TargetRegister, DiceCount, DiceSideCount],
            GameEventScriptBytecodeOpCode.CreateVector => [TargetRegister, ComponentCount],
            GameEventScriptBytecodeOpCode.CreatePoint => [TargetRegister, ComponentCount],
            GameEventScriptBytecodeOpCode.CreateList => [TargetRegister],
            GameEventScriptBytecodeOpCode.CreateMap => [TargetRegister, KeyNameList],
            GameEventScriptBytecodeOpCode.CreateRange => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.CreateRangeWithStep => [TargetRegister, FromRegister, ToRegister, StepRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIterator => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorWithStep => [TargetRegister, FromRegister, ToRegister, StepRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorShort => [TargetRegister, FromImmediate, ToImmediate, StepImmediate],
            GameEventScriptBytecodeOpCode.CreateRecord => [TargetRegister, RecordReference],
            GameEventScriptBytecodeOpCode.CreateRecordValue => [TargetRegister, SourceRegister, CustomTypeName],
            GameEventScriptBytecodeOpCode.CreateExternalType => [TargetRegister, ExternalReference, ArgumentNameList],
            GameEventScriptBytecodeOpCode.HasValue => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.IsEmpty => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Default => [TargetRegister, LeftRegister, RightRegister],

            GameEventScriptBytecodeOpCode.Or => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.And => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Xor => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Implies => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Not => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Equal => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.NotEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Less => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Greater => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.LessOrEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.GreaterOrEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Add => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Subtract => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Multiply => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Divide => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Power => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.IntegerDivide => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Modulo => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Remainder => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Min => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Max => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Negate => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Abs => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.LogN => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Chance => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Clamp => [TargetRegister, SourceRegister, MinimumRegister, MaximumRegister],
            GameEventScriptBytecodeOpCode.RandomTake => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.RandomTakeFloat => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.RandomPush => [SeedRegister],
            GameEventScriptBytecodeOpCode.RandomPushConstant => [IntegerImmediate],
            GameEventScriptBytecodeOpCode.RandomPop => [],
            GameEventScriptBytecodeOpCode.Term => [TargetRegister, SeriesRegister, IndexRegister],
            GameEventScriptBytecodeOpCode.Exp => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Floor => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Ceil => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Truncate => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.RoundHalfEven => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.RoundHalfUp => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.RoundHalfDown => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.DegreeToRadians => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.DegreeFromRadians => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.WrapDegree => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Sin => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Cos => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Tan => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Asin => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Acos => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Atan => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Atan2 => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Hypot2D => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Hypot3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister],
            GameEventScriptBytecodeOpCode.Distance => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Distance2D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister],
            GameEventScriptBytecodeOpCode.Distance3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister, AuxCRegister, AuxDRegister],
            GameEventScriptBytecodeOpCode.DistanceSquared => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.DistanceSquared2D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister],
            GameEventScriptBytecodeOpCode.DistanceSquared3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister, AuxCRegister, AuxDRegister],
            GameEventScriptBytecodeOpCode.LengthSquared => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.LengthSquared2D => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.LengthSquared3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister],
            GameEventScriptBytecodeOpCode.Normalize => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Normalize2D => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Normalize3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister],
            GameEventScriptBytecodeOpCode.Dot => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Dot2D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister],
            GameEventScriptBytecodeOpCode.Dot3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister, AuxCRegister, AuxDRegister],
            GameEventScriptBytecodeOpCode.Cross => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Cross2D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister],
            GameEventScriptBytecodeOpCode.Cross3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister, AuxCRegister, AuxDRegister],
            GameEventScriptBytecodeOpCode.AngleBetween => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.AngleBetween2D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister],
            GameEventScriptBytecodeOpCode.AngleBetween3D => [TargetRegister, LeftRegister, RightRegister, AuxARegister, AuxBRegister, AuxCRegister, AuxDRegister],
            GameEventScriptBytecodeOpCode.TakeFirst => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropFirst => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeLast => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropLast => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeHighest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeLowest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropHighest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropLowest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.OneRandom => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.TakeRandom => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.OneWeighted => [TargetRegister, SourceRegister, WeightRegister],
            GameEventScriptBytecodeOpCode.TakeWeighted => [TargetRegister, SourceRegister, CountImmediate, WeightRegister],

            GameEventScriptBytecodeOpCode.Count => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.StartsWith => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.EndsWith => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Contains => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.ContainsAny => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.ContainsAll => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.ContainsValue => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Union => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Intersect => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Zip => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.KeysOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.ValuesOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.EntriesOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.First => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Last => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Single => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.IteratorCreate => [TargetRegister, CollectionRegister],
            GameEventScriptBytecodeOpCode.IteratorCreateOrJump => [TargetRegister, CollectionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.IteratorNext => [TargetRegister, IteratorRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.IteratorClose => [IteratorRegister],

            GameEventScriptBytecodeOpCode.HasAny => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.HasAll => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.Distinct => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.SortAscending => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.SortDescending => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.Reverse => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.Shuffle => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.ListBuilderCreate => [TargetRegister],
            GameEventScriptBytecodeOpCode.ListBuilderAdd => [BuilderRegister, ItemRegister],
            GameEventScriptBytecodeOpCode.ListBuilderFinish => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.MapBuilderCreate => [TargetRegister],
            GameEventScriptBytecodeOpCode.MapBuilderAdd => [BuilderRegister, KeyRegister, ValueRegister],
            GameEventScriptBytecodeOpCode.MapBuilderFinish => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.DistinctBuilderCreate => [TargetRegister],
            GameEventScriptBytecodeOpCode.DistinctBuilderAdd => [BuilderRegister, KeyRegister, ValueRegister],
            GameEventScriptBytecodeOpCode.DistinctBuilderFinish => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.GroupBuilderCreate => [TargetRegister],
            GameEventScriptBytecodeOpCode.GroupBuilderAdd => [BuilderRegister, KeyRegister, ValueRegister],
            GameEventScriptBytecodeOpCode.GroupBuilderFinish => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.OrderBuilderCreate => [TargetRegister],
            GameEventScriptBytecodeOpCode.OrderBuilderAdd => [BuilderRegister, KeyRegister, ValueRegister],
            GameEventScriptBytecodeOpCode.OrderBuilderFinishAscending => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.OrderBuilderFinishDescending => [TargetRegister, BuilderRegister],
            GameEventScriptBytecodeOpCode.HasPattern => instruction.AU == (ushort)GameEventScriptBytecodePatternKind.CountFace
                ? [TargetRegister, IteratorRegister, PatternKind, CountImmediate, FaceRegister]
                : instruction.AU == (ushort)GameEventScriptBytecodePatternKind.CountAny
                    ? [TargetRegister, IteratorRegister, PatternKind, CountImmediate]
                    : [TargetRegister, IteratorRegister, PatternKind],
            GameEventScriptBytecodeOpCode.TakePattern => instruction.AU == (ushort)GameEventScriptBytecodePatternKind.CountFace
                ? [TargetRegister, IteratorRegister, PatternKind, CountImmediate, FaceRegister]
                : instruction.AU == (ushort)GameEventScriptBytecodePatternKind.CountAny
                    ? [TargetRegister, IteratorRegister, PatternKind, CountImmediate]
                    : [TargetRegister, IteratorRegister, PatternKind],

            _ => throw new ArgumentOutOfRangeException(nameof(instruction.OpCode), instruction.OpCode, null)
        };
    }
}
