<!-- Copyright 2026 Stephan Schlöpke -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<Project>
    <Import Project="../../../../Directory.Build.props" />
    <PropertyGroup>
        <GesConsumerMode>projects</GesConsumerMode>
        <GesConsumerMode Condition="'$(GesUsePackages)' == 'true'">packages</GesConsumerMode>
        <GesConsumerMode Condition="'$(GesUseUnityDlls)' == 'true'">unity</GesConsumerMode>
        <BaseOutputPath>$(MSBuildThisFileDirectory)../../../../artifacts/csharp/runtime-consumer/$(GesConsumerMode)/bin/</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../../../../artifacts/csharp/runtime-consumer/$(GesConsumerMode)/obj/</BaseIntermediateOutputPath>
    </PropertyGroup>
</Project>
