#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using StepH.GameEventScript.Api;
using static StepH.GameEventScript.Extensions.GameEventScriptOpcodePrinter.OpcodeOperands;

namespace StepH.GameEventScript.Extensions;

// ReSharper disable InconsistentNaming
public class GameEventScriptOpcodePrinter
{
    
    internal enum OpcodeOperands
    {
        DST_U16_TargetSlot,
        DST_U16_MessageDestination,

        A_U16_SourceSlot,
        B_U16_SourceSlot,
        C_U16_SourceSlot,
        D_U16_SourceSlot,

        A_U16_LeftSlot,
        B_U16_RightSlot,
        A_U16_OperandSlot,
        A_U16_ReturnSlot,
        A_U16_MessageSlot,
        A_U16_BuilderSlot,
        B_U16_ItemSlot,
        XSlot_PropertySlot,
        XSlot_HandlerSlot,
        YSlot_ObjectSlot,
        A_U16_CollectionSlot,
        A_U16_IteratorSlot,
        A_U16_SourceIteratorSlot,
        A_U16_SeriesSlot,
        B_U16_IndexSlot,
        SecondaryListIndex,
        ListIndex,
        B_U16_DefaultSlot,
        B_U16_SeedSlot,
        B_U16_NeedleSlot,
        B_U16_ItemBindingSlot,
        C_U16_ItemBindingSlot,

        A_U16_Count,
        X_I16_Immediate,
        X_I16_Count,
        Y_I16_Immediate,
        B_U16_Count,

        A_U16_TargetAddress,
        B_U16_TargetAddress,
        TargetAddress,
        B_U16_NextEntryAddress,
        C_U16_TargetAddress,
        C_U16_EntryAddress,
        C_U16_KeyEntryAddress,
        C_U16_ReducerEntryAddress,
        C_U16_FaceEntryAddress,
        D_U16_TargetAddress,
        D_U16_ReducerEntryAddress,
        D_U16_ValueEntryAddress,
        D_U16_WeightEntryAddress,

        C_U16_ConditionSlot,
        ConditionSlot,

        A_U16_FromSlot,
        B_U16_ToSlot,
        C_U16_StepSlot,
        A_I16_FromImmediate,
        B_I16_ToImmediate,
        C_I16_StepImmediate,

        I64_IntegerImmediate,
        F64_FloatImmediate,
        UnitAndFlags_Unit,

        A_U16_StringPoolIndex,
        StringIndex,
        C_U16_StringPoolIndex,
        B_U16_TypeKind,
        B_U16_CustomTypeNameIndex,
        C_U16_CustomTypeNameIndex,

        A_U16_MessageShapeListIndex,
        A_U16_TypeNameIndex,
        A_U16_ItemSlotListIndex,
        A_U16_KeyNameListIndex,
        A_U16_ExternalReferenceIndex,
        A_U16_StandardExtensionShapeListIndex,
        A_U16_CallableEntryAddress,
        A_U16_PredicateEntryAddress,
        EntryAddress_Callable,
        EntryAddress_Predicate,

        B_U16_ArgumentNameListIndex,
        B_U16_ArgumentSlotListIndex,
        B_U16_ValueSlotListIndex,

        C_U16_ArgumentSlotListIndex,
        D_U16_CaptureSlotListIndex
    }

    internal static OpcodeOperands[] PrintInstruction(GameEventScriptBytecodeInstruction instruction)
    {
        return instruction.OpCode switch
        {
            GameEventScriptBytecodeOpCode.Nop => [],
            GameEventScriptBytecodeOpCode.Jump => [TargetAddress],
            GameEventScriptBytecodeOpCode.JumpIfTrue => [TargetAddress, ConditionSlot],
            GameEventScriptBytecodeOpCode.JumpIfFalse => [TargetAddress, ConditionSlot],
            GameEventScriptBytecodeOpCode.JumpIfNotTrue => [TargetAddress, ConditionSlot],
            GameEventScriptBytecodeOpCode.Call => [DST_U16_TargetSlot, EntryAddress_Callable],
            GameEventScriptBytecodeOpCode.ReturnVoid => [],
            GameEventScriptBytecodeOpCode.ReturnValue => [A_U16_ReturnSlot],
            GameEventScriptBytecodeOpCode.CallStandard => [DST_U16_TargetSlot, A_U16_StandardExtensionShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.CallExternal => [DST_U16_TargetSlot, A_U16_ExternalReferenceIndex, B_U16_ArgumentSlotListIndex],

            GameEventScriptBytecodeOpCode.LoadNothing => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadTrue => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadFalse => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadInteger => [DST_U16_TargetSlot, I64_IntegerImmediate],
            GameEventScriptBytecodeOpCode.LoadFloat => [DST_U16_TargetSlot, F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.LoadPercentage => [DST_U16_TargetSlot, F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.LoadText => [DST_U16_TargetSlot, StringIndex],
            GameEventScriptBytecodeOpCode.LoadTag => [DST_U16_TargetSlot, StringIndex],

            GameEventScriptBytecodeOpCode.StageRegister => [A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.StageNothing => [],
            GameEventScriptBytecodeOpCode.StageTrue => [],
            GameEventScriptBytecodeOpCode.StageFalse => [],
            GameEventScriptBytecodeOpCode.StageInteger => [I64_IntegerImmediate],
            GameEventScriptBytecodeOpCode.StageFloat => [F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.StagePercentage => [F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.StageText => [StringIndex],
            GameEventScriptBytecodeOpCode.StageTag => [StringIndex],

            GameEventScriptBytecodeOpCode.MoveSlot => [DST_U16_TargetSlot, A_U16_SourceSlot],

            GameEventScriptBytecodeOpCode.Default => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],

            GameEventScriptBytecodeOpCode.Or => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.And => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Xor => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Not => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Implies => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],

            GameEventScriptBytecodeOpCode.HasValue => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Equal => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.NotEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.ApproxEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Less => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Greater => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.LessOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.GreaterOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IsEmpty => [DST_U16_TargetSlot, A_U16_OperandSlot],

            GameEventScriptBytecodeOpCode.Add => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Subtract => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Multiply => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Divide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Power => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntegerDivide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Modulo => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Remainder => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Negate => [DST_U16_TargetSlot, A_U16_OperandSlot],

            GameEventScriptBytecodeOpCode.Length => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Chance => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Abs => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.LogN => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Clamp => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_SourceSlot, C_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.RandomTake => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.CreateDice => [DST_U16_TargetSlot, X_I16_Count, Y_I16_Immediate],
            GameEventScriptBytecodeOpCode.RandomPush => [A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.RandomPushConstant => [I64_IntegerImmediate],
            GameEventScriptBytecodeOpCode.RandomPop => [],
            GameEventScriptBytecodeOpCode.CreateRange => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.CreateRangeWithStep => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot, C_U16_StepSlot],

            GameEventScriptBytecodeOpCode.Contains => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.ContainsValue => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.StartsWith => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.EndsWith => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Intersect => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Combine => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Except => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Zip => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Min => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Max => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.KeysOfMap => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.ValuesOfMap => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.EntriesOfMap => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.SlotLocals => [X_I16_Count],

            GameEventScriptBytecodeOpCode.Cast => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_TypeKind],
            GameEventScriptBytecodeOpCode.CastNumeric => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastCustom => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_CustomTypeNameIndex],
            GameEventScriptBytecodeOpCode.CastUnit => [DST_U16_TargetSlot, A_U16_SourceSlot, UnitAndFlags_Unit],
            GameEventScriptBytecodeOpCode.CheckType => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_TypeKind],
            GameEventScriptBytecodeOpCode.CheckNumeric => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CheckInteger => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CheckFractional => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CheckCustomType => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_CustomTypeNameIndex],
            GameEventScriptBytecodeOpCode.CheckUnit => [DST_U16_TargetSlot, A_U16_SourceSlot, UnitAndFlags_Unit],

            GameEventScriptBytecodeOpCode.LoadHandler => [DST_U16_TargetSlot, A_U16_MessageShapeListIndex],
            GameEventScriptBytecodeOpCode.CreateRecord => [DST_U16_TargetSlot, A_U16_TypeNameIndex, B_U16_ArgumentNameListIndex],
            GameEventScriptBytecodeOpCode.CreateExternalType => [DST_U16_TargetSlot, A_U16_ExternalReferenceIndex, B_U16_ArgumentNameListIndex],
            GameEventScriptBytecodeOpCode.CreateVector => [DST_U16_TargetSlot, X_I16_Immediate],
            GameEventScriptBytecodeOpCode.CreatePoint => [DST_U16_TargetSlot, X_I16_Immediate],
            GameEventScriptBytecodeOpCode.MemberAccess => [DST_U16_TargetSlot, StringIndex, YSlot_ObjectSlot],
            GameEventScriptBytecodeOpCode.IndexAccess => [DST_U16_TargetSlot, X_I16_Immediate, YSlot_ObjectSlot],
            GameEventScriptBytecodeOpCode.PropertyAccess => [DST_U16_TargetSlot, XSlot_PropertySlot, YSlot_ObjectSlot],
            GameEventScriptBytecodeOpCode.CreateList => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.CreateMap => [DST_U16_TargetSlot, A_U16_KeyNameListIndex],
            GameEventScriptBytecodeOpCode.LoadMessage => [DST_U16_TargetSlot, SecondaryListIndex, ListIndex],
            GameEventScriptBytecodeOpCode.BindHandler => [DST_U16_TargetSlot, XSlot_HandlerSlot, ListIndex],

            GameEventScriptBytecodeOpCode.EmitMessage => [DST_U16_MessageDestination, ListIndex],
            GameEventScriptBytecodeOpCode.EmitMessageWithTags => [DST_U16_MessageDestination, SecondaryListIndex, ListIndex],
            GameEventScriptBytecodeOpCode.PublishMessage => [DST_U16_MessageDestination, ListIndex],
            GameEventScriptBytecodeOpCode.PublishMessageWithTags => [DST_U16_MessageDestination, SecondaryListIndex, ListIndex],
            GameEventScriptBytecodeOpCode.EmitMessageValue => [A_U16_MessageSlot],
            GameEventScriptBytecodeOpCode.EmitMessageValueWithTags => [A_U16_MessageSlot, ListIndex],
            GameEventScriptBytecodeOpCode.PublishMessageValue => [A_U16_MessageSlot],
            GameEventScriptBytecodeOpCode.PublishMessageValueWithTags => [A_U16_MessageSlot, ListIndex],

            GameEventScriptBytecodeOpCode.CreateRangeIterator => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorWithStep => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot, C_U16_StepSlot],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorShort => [DST_U16_TargetSlot, A_I16_FromImmediate, B_I16_ToImmediate, C_I16_StepImmediate],
            GameEventScriptBytecodeOpCode.StreamCreate => [DST_U16_TargetSlot, A_U16_CollectionSlot],
            GameEventScriptBytecodeOpCode.StreamNext => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_TargetAddress],
            GameEventScriptBytecodeOpCode.StreamClose => [A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineListCreateBuilder => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.PipelineListBuilderAdd => [A_U16_BuilderSlot, B_U16_ItemSlot],
            GameEventScriptBytecodeOpCode.PipelineListBuilderFinish => [DST_U16_TargetSlot, A_U16_BuilderSlot],
            GameEventScriptBytecodeOpCode.StreamReduce => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.StreamReduceOrDefault => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_DefaultSlot, C_U16_ItemBindingSlot, D_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.StreamFold => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_SeedSlot, C_U16_ItemBindingSlot, D_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.StreamCollectList => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.StreamCollectMap => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.StreamCollectMapValue => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress, D_U16_ValueEntryAddress],
            GameEventScriptBytecodeOpCode.StreamCollectFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.StreamCollectLast => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.StreamCollectSingle => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.SeriesTerm => [DST_U16_TargetSlot, A_U16_SeriesSlot, B_U16_IndexSlot],
            GameEventScriptBytecodeOpCode.SeriesTake => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.SeriesDrop => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_Count],

            GameEventScriptBytecodeOpCode.PipelineStream => [DST_U16_TargetSlot, A_U16_SourceIteratorSlot, B_U16_NextEntryAddress, C_U16_ItemBindingSlot, D_U16_CaptureSlotListIndex],
            GameEventScriptBytecodeOpCode.PipelineHasAny => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineHasAll => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsSingle => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsAll => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineDistinct => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDistinctBy => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineGroupBy => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineReverse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineSortAscending => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineSortDescending => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineOrderByAscending => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineOrderByDescending => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineTakeFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeLast => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeHighest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeLowest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropLast => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropHighest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropLowest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineShuffle => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDraw => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChoose => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChooseRandom => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChooseWeighted => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_ItemBindingSlot, D_U16_WeightEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountFace => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_FaceEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineDicePatternFullHouse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDicePatternStraight => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountFace => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_FaceEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineTakePatternFullHouse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineTakePatternStraight => [DST_U16_TargetSlot, A_U16_IteratorSlot],

            _ => throw new ArgumentOutOfRangeException(nameof(instruction.OpCode), instruction.OpCode, null)
        };
    }
}
