#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using StepH.GameEventScript.Api;
using static StepH.GameEventScript.Extensions.GameEventScriptOpcodePrinter.OperandPart;

namespace StepH.GameEventScript.Extensions;

// ReSharper disable InconsistentNaming
public class GameEventScriptOpcodePrinter
{
    internal enum OperandPart
    {
        TargetRegister,
        OutboundMessage,

        SourceRegister,
        LeftRegister,
        RightRegister,
        OperandRegister,
        ReturnRegister,
        MessageRegister,
        HandlerRegister,
        PropertyRegister,
        ObjectRegister,
        BuilderRegister,
        ItemRegister,
        ItemBindingRegister,
        ConditionRegister,
        CollectionRegister,
        IteratorRegister,
        SourceIteratorRegister,
        SeriesRegister,
        IndexRegister,
        DefaultRegister,
        SeedRegister,
        NeedleRegister,
        FromRegister,
        ToRegister,
        StepRegister,
        MinimumRegister,
        MaximumRegister,

        LocalRegisterDelta,
        DiceCount,
        DiceSideCount,
        ComponentCount,
        CountImmediate,
        IndexImmediate,
        FromImmediate,
        ToImmediate,
        StepImmediate,
        IntegerImmediate,
        FloatImmediate,
        Unit,

        JumpTarget,
        EntryTarget,
        CallableEntry,
        PredicateEntry,
        NextEntry,
        ProjectionEntry,
        KeyEntry,
        ValueEntry,
        FaceEntry,
        WeightEntry,

        String,
        Text,
        Tag,
        MemberName,
        TypeKind,
        CustomTypeName,
        TypeName,

        MessageShapeList,
        StandardExtensionShapeList,
        ArgumentNameList,
        ArgumentRegisterList,
        ItemRegisterList,
        KeyNameList,
        ValueRegisterList,
        CaptureRegisterList,
        TagRegisterList,
        RecordReference,
        ExternalReference
    }

    internal static OperandPart[] PrintInstruction(GameEventScriptBytecodeInstruction instruction)
    {
        return instruction.OpCode switch
        {
            GameEventScriptBytecodeOpCode.Nop => [],
            GameEventScriptBytecodeOpCode.SlotLocals => [LocalRegisterDelta],
            GameEventScriptBytecodeOpCode.Jump => [JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfTrue => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfFalse => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.JumpIfNotTrue => [ConditionRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.Call => [TargetRegister, CallableEntry],
            GameEventScriptBytecodeOpCode.CallStandard => [TargetRegister, StandardExtensionShapeList, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.CallExternal => [TargetRegister, ExternalReference, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.ReturnVoid => [],
            GameEventScriptBytecodeOpCode.ReturnValue => [ReturnRegister],

            GameEventScriptBytecodeOpCode.EmitMessage => [OutboundMessage, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.EmitMessageWithTags => [OutboundMessage, ArgumentRegisterList, TagRegisterList],
            GameEventScriptBytecodeOpCode.EmitMessageValue => [MessageRegister],
            GameEventScriptBytecodeOpCode.EmitMessageValueWithTags => [MessageRegister, TagRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessage => [OutboundMessage, ArgumentRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessageWithTags => [OutboundMessage, ArgumentRegisterList, TagRegisterList],
            GameEventScriptBytecodeOpCode.PublishMessageValue => [MessageRegister],
            GameEventScriptBytecodeOpCode.PublishMessageValueWithTags => [MessageRegister, TagRegisterList],

            GameEventScriptBytecodeOpCode.Cast => [TargetRegister, SourceRegister, TypeKind],
            GameEventScriptBytecodeOpCode.CastCustom => [TargetRegister, SourceRegister, CustomTypeName],
            GameEventScriptBytecodeOpCode.CastUnit => [TargetRegister, SourceRegister, Unit],
            GameEventScriptBytecodeOpCode.CastNumeric => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckType => [TargetRegister, SourceRegister, TypeKind],
            GameEventScriptBytecodeOpCode.CheckCustomType => [TargetRegister, SourceRegister, CustomTypeName],
            GameEventScriptBytecodeOpCode.CheckUnit => [TargetRegister, SourceRegister, Unit],
            GameEventScriptBytecodeOpCode.CheckNumeric => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckInteger => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.CheckFractional => [TargetRegister, SourceRegister],

            GameEventScriptBytecodeOpCode.MoveSlot => [TargetRegister, SourceRegister],
            GameEventScriptBytecodeOpCode.MemberAccess => [TargetRegister, MemberName, ObjectRegister],
            GameEventScriptBytecodeOpCode.IndexAccess => [TargetRegister, IndexImmediate, ObjectRegister],
            GameEventScriptBytecodeOpCode.PropertyAccess => [TargetRegister, PropertyRegister, ObjectRegister],
            GameEventScriptBytecodeOpCode.BindHandler => [TargetRegister, HandlerRegister, ArgumentRegisterList],

            GameEventScriptBytecodeOpCode.LoadNothing => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadTrue => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadFalse => [TargetRegister],
            GameEventScriptBytecodeOpCode.LoadInteger => [TargetRegister, IntegerImmediate, Unit],
            GameEventScriptBytecodeOpCode.LoadFloat => [TargetRegister, FloatImmediate, Unit],
            GameEventScriptBytecodeOpCode.LoadPercentage => [TargetRegister, FloatImmediate],
            GameEventScriptBytecodeOpCode.LoadText => [TargetRegister, Text],
            GameEventScriptBytecodeOpCode.LoadTag => [TargetRegister, Tag],
            GameEventScriptBytecodeOpCode.LoadHandler => [TargetRegister, MessageShapeList],
            GameEventScriptBytecodeOpCode.LoadMessage => [TargetRegister, MessageShapeList, ArgumentRegisterList],

            GameEventScriptBytecodeOpCode.StageRegister => [SourceRegister],
            GameEventScriptBytecodeOpCode.StageNothing => [],
            GameEventScriptBytecodeOpCode.StageTrue => [],
            GameEventScriptBytecodeOpCode.StageFalse => [],
            GameEventScriptBytecodeOpCode.StageInteger => [IntegerImmediate, Unit],
            GameEventScriptBytecodeOpCode.StageFloat => [FloatImmediate, Unit],
            GameEventScriptBytecodeOpCode.StageText => [Text],
            GameEventScriptBytecodeOpCode.StageTag => [Tag],
            GameEventScriptBytecodeOpCode.StagePercentage => [FloatImmediate],

            GameEventScriptBytecodeOpCode.CreateDice => [TargetRegister, DiceCount, DiceSideCount],
            GameEventScriptBytecodeOpCode.CreateVector => [TargetRegister, ComponentCount],
            GameEventScriptBytecodeOpCode.CreatePoint => [TargetRegister, ComponentCount],
            GameEventScriptBytecodeOpCode.CreateList => [TargetRegister],
            GameEventScriptBytecodeOpCode.CreateMap => [TargetRegister, KeyNameList],
            GameEventScriptBytecodeOpCode.CreateRange => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.CreateRangeWithStep => [TargetRegister, FromRegister, ToRegister, StepRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIterator => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorWithStep => [TargetRegister, FromRegister, ToRegister, StepRegister],
            GameEventScriptBytecodeOpCode.CreateRangeIteratorShort => [TargetRegister, FromImmediate, ToImmediate, StepImmediate],
            GameEventScriptBytecodeOpCode.CreateRecord => [TargetRegister, RecordReference],
            GameEventScriptBytecodeOpCode.CreateExternalType => [TargetRegister, ExternalReference, ArgumentNameList],
            GameEventScriptBytecodeOpCode.HasValue => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.IsEmpty => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Default => [TargetRegister, LeftRegister, RightRegister],

            GameEventScriptBytecodeOpCode.Or => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.And => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Xor => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Implies => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Not => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Equal => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.NotEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Less => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Greater => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.LessOrEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.GreaterOrEqual => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Add => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Subtract => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Multiply => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Divide => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Power => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.IntegerDivide => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Modulo => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Remainder => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Min => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Max => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Negate => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Abs => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.LogN => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Chance => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Clamp => [TargetRegister, SourceRegister, MinimumRegister, MaximumRegister],
            GameEventScriptBytecodeOpCode.RandomTake => [TargetRegister, FromRegister, ToRegister],
            GameEventScriptBytecodeOpCode.RandomPush => [SeedRegister],
            GameEventScriptBytecodeOpCode.RandomPushConstant => [IntegerImmediate],
            GameEventScriptBytecodeOpCode.RandomPop => [],
            GameEventScriptBytecodeOpCode.Term => [TargetRegister, SeriesRegister, IndexRegister],
            GameEventScriptBytecodeOpCode.TakeFirst => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropFirst => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeLast => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropLast => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeHighest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.TakeLowest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropHighest => [TargetRegister, SourceRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.DropLowest => [TargetRegister, SourceRegister, CountImmediate],

            GameEventScriptBytecodeOpCode.Length => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.StartsWith => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.EndsWith => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Contains => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.ContainsValue => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Union => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Intersect => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.Zip => [TargetRegister, LeftRegister, RightRegister],
            GameEventScriptBytecodeOpCode.KeysOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.ValuesOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.EntriesOfMap => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.First => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Last => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.Single => [TargetRegister, OperandRegister],
            GameEventScriptBytecodeOpCode.StreamCreate => [TargetRegister, CollectionRegister],
            GameEventScriptBytecodeOpCode.StreamNext => [TargetRegister, IteratorRegister, JumpTarget],
            GameEventScriptBytecodeOpCode.StreamClose => [IteratorRegister],
            GameEventScriptBytecodeOpCode.StreamMap => [TargetRegister, SourceIteratorRegister, NextEntry, ItemBindingRegister, CaptureRegisterList],
            GameEventScriptBytecodeOpCode.StreamFilter => [TargetRegister, SourceIteratorRegister, PredicateEntry, ItemBindingRegister, CaptureRegisterList],
            GameEventScriptBytecodeOpCode.StreamCount => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.StreamSum => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.StreamAverage => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.StreamMin => [TargetRegister, IteratorRegister, ItemBindingRegister, ProjectionEntry],
            GameEventScriptBytecodeOpCode.StreamMax => [TargetRegister, IteratorRegister, ItemBindingRegister, ProjectionEntry],
            GameEventScriptBytecodeOpCode.StreamCollectList => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.StreamCollectMap => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry],
            GameEventScriptBytecodeOpCode.StreamCollectMapValue => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry, ValueEntry],

            GameEventScriptBytecodeOpCode.PipelineHasAny => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineHasAll => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineContainsSingle => [TargetRegister, IteratorRegister, NeedleRegister],
            GameEventScriptBytecodeOpCode.PipelineContainsAny => [TargetRegister, IteratorRegister, NeedleRegister],
            GameEventScriptBytecodeOpCode.PipelineContainsAll => [TargetRegister, IteratorRegister, NeedleRegister],
            GameEventScriptBytecodeOpCode.PipelineDistinct => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineDistinctBy => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry],
            GameEventScriptBytecodeOpCode.PipelineGroupBy => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry],
            GameEventScriptBytecodeOpCode.PipelineReverse => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineSortAscending => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineSortDescending => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineOrderByAscending => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry],
            GameEventScriptBytecodeOpCode.PipelineOrderByDescending => [TargetRegister, IteratorRegister, ItemBindingRegister, KeyEntry],
            GameEventScriptBytecodeOpCode.PipelineShuffle => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineChoose => [TargetRegister, IteratorRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.PipelineChooseRandom => [TargetRegister, IteratorRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.PipelineChooseWeighted => [TargetRegister, IteratorRegister, CountImmediate, ItemBindingRegister, WeightEntry],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountAny => [TargetRegister, IteratorRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountFace => [TargetRegister, IteratorRegister, CountImmediate, FaceEntry],
            GameEventScriptBytecodeOpCode.PipelineDicePatternFullHouse => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineDicePatternStraight => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountAny => [TargetRegister, IteratorRegister, CountImmediate],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountFace => [TargetRegister, IteratorRegister, CountImmediate, FaceEntry],
            GameEventScriptBytecodeOpCode.PipelineTakePatternFullHouse => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineTakePatternStraight => [TargetRegister, IteratorRegister],
            GameEventScriptBytecodeOpCode.PipelineListCreateBuilder => [TargetRegister],
            GameEventScriptBytecodeOpCode.PipelineListBuilderAdd => [BuilderRegister, ItemRegister],
            GameEventScriptBytecodeOpCode.PipelineListBuilderFinish => [TargetRegister, BuilderRegister],

            _ => throw new ArgumentOutOfRangeException(nameof(instruction.OpCode), instruction.OpCode, null)
        };
    }
}
