#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using StepH.GameEventScript.Api;
using static StepH.GameEventScript.Extensions.GameEventScriptOpcodePrinter.OpcodeOperands;

namespace StepH.GameEventScript.Extensions;

// ReSharper disable InconsistentNaming
public class GameEventScriptOpcodePrinter
{
    
    internal enum OpcodeOperands
    {
        DST_U16_TargetSlot,

        A_U16_SourceSlot,
        B_U16_SourceSlot,
        C_U16_SourceSlot,
        D_U16_SourceSlot,

        A_U16_LeftSlot,
        B_U16_RightSlot,
        A_U16_OperandSlot,
        A_U16_ReturnSlot,
        A_U16_MessageSlot,
        A_U16_BuilderSlot,
        B_U16_ItemSlot,
        A_U16_CollectionSlot,
        A_U16_IteratorSlot,
        A_U16_SourceIteratorSlot,
        A_U16_SeriesSlot,
        B_U16_IndexSlot,
        B_U16_DefaultSlot,
        B_U16_SeedSlot,
        B_U16_NeedleSlot,
        B_U16_ItemBindingSlot,
        C_U16_ItemBindingSlot,

        A_U16_Count,
        B_U16_Count,
        A_U16_DiceCountImmediate,
        B_U16_DiceSideCountImmediate,

        A_U16_TargetAddress,
        B_U16_TargetAddress,
        B_U16_NextEntryAddress,
        C_U16_TargetAddress,
        C_U16_EntryAddress,
        C_U16_KeyEntryAddress,
        C_U16_ReducerEntryAddress,
        C_U16_FaceEntryAddress,
        D_U16_TargetAddress,
        D_U16_ReducerEntryAddress,
        D_U16_ValueEntryAddress,
        D_U16_WeightEntryAddress,

        C_U16_ConditionSlot,

        A_U16_FromSlot,
        B_U16_ToSlot,
        C_U16_StepSlot,
        A_I16_FromImmediate,
        B_I16_ToImmediate,
        C_I16_StepImmediate,

        I64_IntegerImmediate,
        U64_UnsignedIntegerImmediate,
        F64_FloatImmediate,

        A_U16_StringPoolIndex,
        C_U16_StringPoolIndex,

        A_U16_MessageShapeListIndex,
        A_U16_OperationNameIndex,
        A_U16_TypeNameIndex,
        A_U16_ItemSlotListIndex,
        A_U16_KeyNameListIndex,
        A_U16_OperandSlotListIndex,
        A_U16_ExternalReferenceIndex,
        A_U16_StandardExtensionShapeListIndex,
        A_U16_CallableEntryAddress,
        A_U16_PredicateEntryAddress,

        B_U16_ArgumentNameListIndex,
        B_U16_ArgumentSlotListIndex,
        B_U16_ValueSlotListIndex,

        C_U16_ArgumentSlotListIndex,
        C_U16_TagSlotListIndex,

        D_U16_CaptureSlotListIndex
    }

    internal static OpcodeOperands[] PrintInstruction(GameEventScriptBytecodeInstruction instruction)
    {
        return instruction.OpCode switch
        {
            GameEventScriptBytecodeOpCode.Nop => [],
            GameEventScriptBytecodeOpCode.Jump => [A_U16_TargetAddress],
            GameEventScriptBytecodeOpCode.JumpIfTrue => [A_U16_TargetAddress, C_U16_ConditionSlot],
            GameEventScriptBytecodeOpCode.JumpIfFalse => [A_U16_TargetAddress, C_U16_ConditionSlot],
            GameEventScriptBytecodeOpCode.JumpIfNotTrue => [A_U16_TargetAddress, C_U16_ConditionSlot],
            GameEventScriptBytecodeOpCode.Call => [DST_U16_TargetSlot, A_U16_CallableEntryAddress],
            GameEventScriptBytecodeOpCode.CallPredicate => [DST_U16_TargetSlot, A_U16_PredicateEntryAddress],
            GameEventScriptBytecodeOpCode.ReturnVoid => [],
            GameEventScriptBytecodeOpCode.ReturnValue => [A_U16_ReturnSlot],
            GameEventScriptBytecodeOpCode.CallStandard => [DST_U16_TargetSlot, A_U16_StandardExtensionShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.CallStandardPredicate => [DST_U16_TargetSlot, A_U16_StandardExtensionShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.CallExternal => [DST_U16_TargetSlot, A_U16_ExternalReferenceIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.CallExternalPredicate => [DST_U16_TargetSlot, A_U16_ExternalReferenceIndex, B_U16_ArgumentSlotListIndex],

            GameEventScriptBytecodeOpCode.LoadNothing => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadTrue => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadFalse => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.LoadInteger => [DST_U16_TargetSlot, I64_IntegerImmediate],
            GameEventScriptBytecodeOpCode.LoadFloat => [DST_U16_TargetSlot, F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.LoadText => [DST_U16_TargetSlot, C_U16_StringPoolIndex],
            GameEventScriptBytecodeOpCode.LoadTag => [DST_U16_TargetSlot, C_U16_StringPoolIndex],

            GameEventScriptBytecodeOpCode.StageRegister => [A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.StageNothing => [],
            GameEventScriptBytecodeOpCode.StageTrue => [],
            GameEventScriptBytecodeOpCode.StageFalse => [],
            GameEventScriptBytecodeOpCode.StageInteger => [I64_IntegerImmediate],
            GameEventScriptBytecodeOpCode.StageFloat => [F64_FloatImmediate],
            GameEventScriptBytecodeOpCode.StageText => [C_U16_StringPoolIndex],
            GameEventScriptBytecodeOpCode.StageTag => [C_U16_StringPoolIndex],

            GameEventScriptBytecodeOpCode.MoveSlot => [DST_U16_TargetSlot, A_U16_SourceSlot],

            GameEventScriptBytecodeOpCode.Default => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],

            GameEventScriptBytecodeOpCode.Or => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.And => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Xor => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.UnaryNot => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Implies => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],

            GameEventScriptBytecodeOpCode.UnaryHasValue => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Equal => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.NotEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.ApproxEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Less => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Greater => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.LessOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.GreaterOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.UnaryEmpty => [DST_U16_TargetSlot, A_U16_OperandSlot],

            GameEventScriptBytecodeOpCode.Add => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Subtract => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Multiply => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Divide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Power => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntegerDivide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Modulo => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Remainder => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.UnaryNegate => [DST_U16_TargetSlot, A_U16_OperandSlot],

            GameEventScriptBytecodeOpCode.IntEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntNotEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntLess => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntGreater => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntLessOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntGreaterOrEqual => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntAdd => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntSubtract => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntMultiply => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntDivide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntFloorDivide => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntModulo => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.IntRemainder => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],

            GameEventScriptBytecodeOpCode.UnaryLength => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.UnaryChance => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.UnaryAbs => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.UnaryNaturalLog => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.Clamp => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_SourceSlot, C_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.Random => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.Dice => [DST_U16_TargetSlot, A_U16_DiceCountImmediate, B_U16_DiceSideCountImmediate],
            GameEventScriptBytecodeOpCode.RandomPush => [A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.RandomPushConstant => [U64_UnsignedIntegerImmediate],
            GameEventScriptBytecodeOpCode.RandomPop => [],
            GameEventScriptBytecodeOpCode.Range => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.RangeWithStep => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot, C_U16_StepSlot],

            GameEventScriptBytecodeOpCode.Contains => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.ContainsValue => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.StartsWith => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.EndsWith => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Intersect => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Combine => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Except => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.Zip => [DST_U16_TargetSlot, A_U16_LeftSlot, B_U16_RightSlot],
            GameEventScriptBytecodeOpCode.UnaryKeys => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.UnaryValues => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.UnaryEntries => [DST_U16_TargetSlot, A_U16_OperandSlot],
            GameEventScriptBytecodeOpCode.ReserveSlots => [A_U16_Count],

            GameEventScriptBytecodeOpCode.CastNothing => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastBoolean => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastInteger => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastFloat => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastNumber => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastPercentage => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastDegree => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastMeter => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastSecond => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastVector => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastPoint => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastUuid => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastOptional => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastCustom => [DST_U16_TargetSlot, A_U16_SourceSlot, C_U16_StringPoolIndex],
            GameEventScriptBytecodeOpCode.CastSeries => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastEnvelope => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastRef => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastTag => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastText => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastList => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastRange => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastMessage => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastHandler => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastMap => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastSet => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.CastDice => [DST_U16_TargetSlot, A_U16_SourceSlot],

            GameEventScriptBytecodeOpCode.TypeCheckNothing => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckBoolean => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckInteger => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckFloat => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckPercentage => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckDegree => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckMeter => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckSecond => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckVector => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckPoint => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckUuid => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckOptional => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckTag => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckText => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckCustom => [DST_U16_TargetSlot, A_U16_SourceSlot, C_U16_StringPoolIndex],
            GameEventScriptBytecodeOpCode.TypeCheckSeries => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckEnvelope => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckList => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckRange => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckMessage => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckHandler => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckRef => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckMap => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckSet => [DST_U16_TargetSlot, A_U16_SourceSlot],
            GameEventScriptBytecodeOpCode.TypeCheckDice => [DST_U16_TargetSlot, A_U16_SourceSlot],

            GameEventScriptBytecodeOpCode.LoadHandler => [DST_U16_TargetSlot, A_U16_MessageShapeListIndex],
            GameEventScriptBytecodeOpCode.TypeConstructor => [DST_U16_TargetSlot, A_U16_TypeNameIndex, B_U16_ArgumentNameListIndex, C_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.MemberAccess => [DST_U16_TargetSlot, A_U16_SourceSlot, C_U16_StringPoolIndex],
            GameEventScriptBytecodeOpCode.IndexedAccess => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_IndexSlot],
            GameEventScriptBytecodeOpCode.BuildList => [DST_U16_TargetSlot, A_U16_ItemSlotListIndex],
            GameEventScriptBytecodeOpCode.BuildSet => [DST_U16_TargetSlot, A_U16_ItemSlotListIndex],
            GameEventScriptBytecodeOpCode.BuildMap => [DST_U16_TargetSlot, A_U16_KeyNameListIndex, B_U16_ValueSlotListIndex],
            GameEventScriptBytecodeOpCode.BuildMessage => [DST_U16_TargetSlot, A_U16_MessageShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.BindHandler => [DST_U16_TargetSlot, A_U16_OperandSlotListIndex, B_U16_ArgumentNameListIndex],
            GameEventScriptBytecodeOpCode.Variadic => [DST_U16_TargetSlot, A_U16_OperationNameIndex, B_U16_ArgumentSlotListIndex],

            GameEventScriptBytecodeOpCode.ReleaseSlots => [A_U16_Count],
            GameEventScriptBytecodeOpCode.EmitMessage => [A_U16_MessageShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.EmitMessageWithTags => [A_U16_MessageShapeListIndex, B_U16_ArgumentSlotListIndex, C_U16_TagSlotListIndex],
            GameEventScriptBytecodeOpCode.PublishMessage => [A_U16_MessageShapeListIndex, B_U16_ArgumentSlotListIndex],
            GameEventScriptBytecodeOpCode.PublishMessageWithTags => [A_U16_MessageShapeListIndex, B_U16_ArgumentSlotListIndex, C_U16_TagSlotListIndex],
            GameEventScriptBytecodeOpCode.EmitMessageValue => [A_U16_MessageSlot],
            GameEventScriptBytecodeOpCode.EmitMessageValueWithTags => [A_U16_MessageSlot, C_U16_TagSlotListIndex],
            GameEventScriptBytecodeOpCode.PublishMessageValue => [A_U16_MessageSlot],
            GameEventScriptBytecodeOpCode.PublishMessageValueWithTags => [A_U16_MessageSlot, C_U16_TagSlotListIndex],

            GameEventScriptBytecodeOpCode.RangeIterator => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot],
            GameEventScriptBytecodeOpCode.RangeIteratorWithStep => [DST_U16_TargetSlot, A_U16_FromSlot, B_U16_ToSlot, C_U16_StepSlot],
            GameEventScriptBytecodeOpCode.RangeIteratorShort => [DST_U16_TargetSlot, A_I16_FromImmediate, B_I16_ToImmediate, C_I16_StepImmediate],
            GameEventScriptBytecodeOpCode.CollectionIterator => [DST_U16_TargetSlot, A_U16_CollectionSlot],
            GameEventScriptBytecodeOpCode.IteratorNext => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_TargetAddress],
            GameEventScriptBytecodeOpCode.IteratorClose => [A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.CollectionBuilderList => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.CollectionBuilderSet => [DST_U16_TargetSlot],
            GameEventScriptBytecodeOpCode.CollectionBuilderAdd => [A_U16_BuilderSlot, B_U16_ItemSlot],
            GameEventScriptBytecodeOpCode.CollectionBuilderFinish => [DST_U16_TargetSlot, A_U16_BuilderSlot],
            GameEventScriptBytecodeOpCode.IteratorReduce => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.IteratorReduceOrDefault => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_DefaultSlot, C_U16_ItemBindingSlot, D_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.IteratorFold => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_SeedSlot, C_U16_ItemBindingSlot, D_U16_ReducerEntryAddress],
            GameEventScriptBytecodeOpCode.SeriesTerm => [DST_U16_TargetSlot, A_U16_SeriesSlot, B_U16_IndexSlot],
            GameEventScriptBytecodeOpCode.SeriesTake => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.SeriesDrop => [DST_U16_TargetSlot, A_U16_SourceSlot, B_U16_Count],

            GameEventScriptBytecodeOpCode.PipelineIterator => [DST_U16_TargetSlot, A_U16_SourceIteratorSlot, B_U16_NextEntryAddress, C_U16_ItemBindingSlot, D_U16_CaptureSlotListIndex],
            GameEventScriptBytecodeOpCode.PipelineCollectList => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineCollectSet => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineLast => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineSingle => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineHasAny => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineHasAll => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsSingle => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineContainsAll => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_NeedleSlot],
            GameEventScriptBytecodeOpCode.PipelineMap => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineMapValue => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress, D_U16_ValueEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineDistinct => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDistinctBy => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineGroupBy => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineReverse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineSortAscending => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineSortDescending => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineOrderByAscending => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineOrderByDescending => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_ItemBindingSlot, C_U16_KeyEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineTakeFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeLast => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeHighest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakeLowest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropFirst => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropLast => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropHighest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDropLowest => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineShuffle => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDraw => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChoose => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChooseRandom => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineChooseWeighted => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_ItemBindingSlot, D_U16_WeightEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineDicePatternCountFace => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_FaceEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineDicePatternFullHouse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineDicePatternStraight => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountAny => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count],
            GameEventScriptBytecodeOpCode.PipelineTakePatternCountFace => [DST_U16_TargetSlot, A_U16_IteratorSlot, B_U16_Count, C_U16_FaceEntryAddress],
            GameEventScriptBytecodeOpCode.PipelineTakePatternFullHouse => [DST_U16_TargetSlot, A_U16_IteratorSlot],
            GameEventScriptBytecodeOpCode.PipelineTakePatternStraight => [DST_U16_TargetSlot, A_U16_IteratorSlot],

            _ => throw new ArgumentOutOfRangeException(nameof(instruction.OpCode), instruction.OpCode, null)
        };
    }
}
