#!/usr/bin/env python3
# Copyright 2026 Stephan Schlöpke
# SPDX-License-Identifier: Apache-2.0
"""Generate immutable rule tables from the canonical GES/GESA TextMate grammars."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = '// Copyright 2026 Stephan Schlöpke\n// SPDX-License-Identifier: Apache-2.0\n\n'
HEADER += '// Generated by scripts/sync-highlighter-grammars.py; do not edit.\n'


def generate():
    rules = []
    source = []
    allowed = {'match', 'begin', 'end', 'name', 'contentName', 'captures', 'beginCaptures', 'endCaptures', 'patterns', 'include', 'comment', 'applyEndPatternLast'}

    def expand(patterns, repository, visiting=()):
        result = []
        for pattern in patterns:
            unknown = set(pattern) - allowed
            if unknown:
                raise ValueError(f'Unsupported TextMate keys: {unknown}')
            if 'include' in pattern:
                include = pattern['include']
                if include == 'source.gameeventscript':
                    if not source:
                        raise ValueError('Source grammar cannot recursively include itself')
                    result.extend(source)
                elif include.startswith('#') and include not in visiting:
                    result.extend(expand(repository[include[1:]]['patterns'], repository, (*visiting, include)))
                else:
                    raise ValueError(f'Unsupported/cyclic include: {include}')
                continue
            if 'match' not in pattern and 'begin' not in pattern:
                result.extend(expand(pattern.get('patterns', []), repository, visiting))
                continue
            if ('begin' in pattern) != ('end' in pattern):
                raise ValueError('Every begin rule needs an end rule')
            children = expand(pattern.get('patterns', []), repository, visiting)
            index = len(rules)
            rules.append((pattern, children))
            result.append(index)
        return result

    roots = []
    for bundle in ['GameEventScript', 'GameEventScriptAssembler']:
        path = ROOT / f'tools/editors/TextMate/{bundle}.tmbundle/Syntaxes/{bundle}.tmLanguage.json'
        document = json.loads(path.read_text())
        ids = expand(document['patterns'], document['repository'])
        roots.append(ids)
        if not source:
            source = ids

    def captures(pattern, field):
        groups = pattern.get(field, pattern.get('captures', {}) if field != 'captures' else {})
        for group, data in groups.items():
            if set(data) != {'name'} or not group.isdecimal():
                raise ValueError('Only numbered named captures are supported')
        return [(int(k), v['name']) for k, v in sorted(groups.items(), key=lambda pair: int(pair[0]))]

    cs = HEADER + '\nnamespace GameEventScript.SyntaxHighlighter;\n\ninternal static class EmbeddedGrammars\n{\n'
    for name, ids in zip(['Source', 'Assembly'], roots):
        cs += f'    internal static readonly int[] {name} = [{", ".join(map(str, ids))}];\n'
    cs += '\n    internal static GrammarRule[] CreateRules() =>\n    [\n'
    for p, children in rules:
        values = [p.get('match', p.get('begin', '')), p.get('end', ''), p.get('name', ''), p.get('contentName', '')]
        groups = [captures(p, 'captures'), captures(p, 'beginCaptures'), captures(p, 'endCaptures')]
        cs += '        new(\n' + ',\n'.join('            ' + json.dumps(v, ensure_ascii=False) for v in values) + ',\n'
        for pairs in groups:
            cs += '            [' + ', '.join(f'new CaptureRule({i}, {json.dumps(n)})' for i, n in pairs) + '],\n'
        cs += '            [' + ', '.join(map(str, children)) + '], ' + str(bool(p.get('applyEndPatternLast'))).lower() + '),\n'
    cs += '    ];\n}\n'
    payload = {
        'source': roots[0], 'assembly': roots[1],
        'rules': [{
            'pattern': p.get('match', p.get('begin', '')), 'end': p.get('end', ''),
            'name': p.get('name', ''), 'contentName': p.get('contentName', ''),
            'captures': captures(p, 'captures'), 'beginCaptures': captures(p, 'beginCaptures'),
            'endCaptures': captures(p, 'endCaptures'), 'children': children,
            'endLast': bool(p.get('applyEndPatternLast')),
        } for p, children in rules],
    }
    swift = HEADER + '\nenum EmbeddedGrammars {\n    static let json = ####"""\n'
    swift += '\n'.join('        ' + line for line in json.dumps(payload, ensure_ascii=False, indent=2).splitlines())
    swift += '\n        """####\n}\n'
    return {
        ROOT / 'implementation/csharp/GameEventScript.SyntaxHighlighter/src/EmbeddedGrammars.g.cs': cs,
        ROOT / 'implementation/swift/GameEventScriptSyntaxHighlighter/Sources/GameEventScriptSyntaxHighlighter/EmbeddedGrammars.swift': swift,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'{path.relative_to(ROOT)} differs; run scripts/sync-highlighter-grammars.py')
        else:
            path.write_text(text)
    print('C# and Swift highlighting tables match the canonical TextMate grammars.')


if __name__ == '__main__':
    main()
