#!/usr/bin/env python3
# Copyright 2026 Stephan Schlöpke
# SPDX-License-Identifier: Apache-2.0
"""Generate Sublime syntax and shared editor commands/completions from canonical sources."""
import argparse
import json
from pathlib import Path
import plistlib
import uuid
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
EDITORS = ROOT / 'tools/editors'
NOTICE = 'Copyright 2026 Stephan Schlöpke\nSPDX-License-Identifier: Apache-2.0'
SCOPE = 'source.gameeventscript - source.gameeventscript.assembler - comment - string'


def captures(value):
    return {int(key): item['name'] for key, item in value.items()}


def rules(patterns):
    result = []
    for pattern in patterns:
        allowed = {'include', 'match', 'name', 'captures', 'begin', 'end', 'beginCaptures',
                   'endCaptures', 'contentName', 'patterns', 'applyEndPatternLast', 'comment'}
        if pattern.keys() - allowed:
            raise ValueError('Unsupported TextMate pattern keys: ' + str(pattern.keys() - allowed))
        if 'include' in pattern:
            value = pattern['include']
            result.append({'include': value[1:] if value.startswith('#') else 'scope:' + value})
        elif 'match' in pattern:
            rule = {'match': pattern['match']}
            if 'name' in pattern:
                rule['scope'] = pattern['name']
            if 'captures' in pattern:
                rule['captures'] = captures(pattern['captures'])
            result.append(rule)
        elif 'begin' in pattern:
            end = {'match': pattern['end'], 'pop': True}
            if 'endCaptures' in pattern:
                end['captures'] = captures(pattern['endCaptures'])
            children = rules(pattern.get('patterns', []))
            children = children + [end] if pattern.get('applyEndPatternLast') else [end] + children
            metadata = []
            if 'name' in pattern:
                metadata.append({'meta_scope': pattern['name']})
            if 'contentName' in pattern:
                metadata.append({'meta_content_scope': pattern['contentName']})
            rule = {'match': pattern['begin'], 'push': metadata + children}
            if 'beginCaptures' in pattern:
                rule['captures'] = captures(pattern['beginCaptures'])
            result.append(rule)
        elif 'patterns' in pattern:
            result.extend(rules(pattern['patterns']))
        else:
            raise ValueError('Unsupported TextMate pattern: ' + repr(pattern))
    return result


def syntax(grammar):
    return {'name': grammar['name'], 'file_extensions': grammar['fileTypes'],
            'scope': grammar['scopeName'], 'first_line_match': grammar.get('firstLineMatch', ''),
            'contexts': {'main': rules(grammar['patterns']), **{
                key: rules(value['patterns']) for key, value in grammar['repository'].items()}}}


def yaml(value, indent=0):
    """Emit the JSON-compatible YAML subset, preserving integer capture keys."""
    pad = ' ' * indent
    def item(v):
        return '\n' + yaml(v, indent + 2) if isinstance(v, (dict, list)) else ' ' + json.dumps(v, ensure_ascii=False) + '\n'
    if isinstance(value, dict):
        return ''.join(pad + (str(k) if isinstance(k, int) else json.dumps(k)) + ':' + item(v) for k, v in value.items())
    return ''.join(pad + '-' + item(v) for v in value)


def plist(data):
    content = plistlib.dumps(data, sort_keys=False).decode()
    return content.replace('<!DOCTYPE', '<!-- ' + NOTICE.replace('\n', ' -->\n<!-- ') + ' -->\n<!DOCTYPE', 1)


def identity(name):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, 'https://gameeventscript.org/editor/' + name)).upper()


def generate():
    output = {}
    support = EDITORS / 'support'
    completion_text = (support / 'completions.json').read_text()
    data = json.loads(completion_text)
    sublime = EDITORS / 'Sublime Text/GameEventScript'
    output[sublime / 'completions.json'] = completion_text
    output[sublime / 'ges_completions.py'] = (support / 'ges_completions.py').read_text()
    for name in ('GameEventScript', 'GameEventScriptAssembler'):
        grammar = json.loads((EDITORS / 'TextMate' / (name + '.tmbundle') / 'Syntaxes' / (name + '.tmLanguage.json')).read_text())
        output[sublime / (name + '.sublime-syntax')] = '%YAML 1.2\n---\n# ' + NOTICE.replace('\n', '\n# ') + '\n# Generated by scripts/sync-editor-bundles.py.\n' + yaml(syntax(grammar))
        for variant in ('TextMate', 'TextMate Classic'):
            bundle = EDITORS / variant / (name + '.tmbundle')
            for file in ('ges-command.sh', 'output.pl'):
                output[bundle / 'Support' / file] = (support / file).read_text()
            actions = ('check', 'compile', 'run', 'dump') if name == 'GameEventScript' else ('dump',)
            for action in actions:
                command = {'name': 'GES: ' + action.title(), 'uuid': identity(name + '/' + action),
                           'scope': grammar['scopeName'], 'beforeRunningCommand': 'saveActiveFile',
                           'input': 'none', 'output': 'showAsHTML',
                           'command': '#!/bin/bash\n/bin/bash "$TM_BUNDLE_SUPPORT/ges-command.sh" ' + action + '\n'}
                if action == 'check':
                    command['keyEquivalent'] = '@b'
                output[bundle / 'Commands' / (action.title() + '.tmCommand')] = plist(command)
            if name != 'GameEventScript':
                continue
            for file in ('completions.json', 'complete.pl'):
                output[bundle / 'Support' / file] = (support / file).read_text()
            output[bundle / 'Preferences/Completions.tmPreferences'] = plist({
                'name': 'GES syntax completions', 'uuid': identity('completions'), 'scope': SCOPE,
                'settings': {'completionCommand': '/usr/bin/perl "$TM_BUNDLE_SUPPORT/complete.pl"',
                             'disableDefaultCompletion': True}})
            for snippet in data['snippets']:
                output[bundle / 'Snippets' / (snippet['trigger'] + '.tmSnippet')] = plist({
                    'name': snippet['name'], 'uuid': identity(snippet['trigger']), 'scope': SCOPE,
                    'tabTrigger': snippet['trigger'], 'content': snippet['body']})
    for snippet in data['snippets']:
        output[sublime / (snippet['trigger'] + '.sublime-snippet')] = ('<!-- ' + NOTICE.replace('\n', ' -->\n<!-- ') + ' -->\n<snippet>\n'
            + '<content>' + escape(snippet['body']) + '</content>\n<tabTrigger>' + snippet['trigger']
            + '</tabTrigger>\n<scope>' + SCOPE + '</scope>\n<description>' + snippet['name'] + '</description>\n</snippet>\n')
    build = {'cmd': ['ges', 'check', '$file'], 'selector': 'source.gameeventscript - source.gameeventscript.assembler',
             'working_dir': '$file_path', 'env': {'NO_COLOR': '1'}, 'encoding': 'utf-8',
             'file_regex': r'^(.*)\(([0-9]+),([0-9]+)\): (.*)$',
             'variants': [{'name': action.title(), 'cmd': ['ges', action, '$file']} for action in ('compile', 'run')]
                         + [{'name': 'Dump', 'cmd': ['ges', 'dump', '${file_path}/${file_base_name}.gesb']}]}
    output[sublime / 'GameEventScript.sublime-build'] = '// ' + NOTICE.replace('\n', '\n// ') + '\n' + json.dumps(build, indent=2) + '\n'
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(str(path.relative_to(ROOT)) + ' is stale; run scripts/sync-editor-bundles.py')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print('Sublime grammars and editor commands/completions are synchronized.')


if __name__ == '__main__':
    main()
