#!/usr/bin/env python3
# Copyright 2026 Stephan Schlöpke
# SPDX-License-Identifier: Apache-2.0
"""Embed the canonical TextMate grammars in the standalone Swift executable."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Verify the checked-in copy without writing it')
args = parser.parse_args()
text = '// Copyright 2026 Stephan Schlöpke\n// SPDX-License-Identifier: Apache-2.0\n\n'
text += '// Generated by scripts/sync-swift-cli-grammars.py; normal builds need no generator.\n'
text += 'enum EmbeddedGrammars {\n'
for field, bundle in [('source', 'GameEventScript'), ('assembly', 'GameEventScriptAssembler')]:
    grammar = root / f'tools/editors/TextMate/{bundle}.tmbundle/Syntaxes/{bundle}.tmLanguage.json'
    text += f'    static let {field} = ####"""\n'
    text += '\n'.join('        ' + line for line in grammar.read_text().rstrip().splitlines())
    text += '\n        """####\n'
text += '}\n'
output = root / 'implementation/swift/GameEventScriptTool/Sources/GameEventScriptTool/EmbeddedGrammars.swift'
if args.check:
    if not output.exists() or output.read_text() != text:
        raise SystemExit('Swift CLI grammars differ. Run python3 scripts/sync-swift-cli-grammars.py.')
    print('Swift CLI grammars match the canonical TextMate sources.')
else:
    output.write_text(text)
