<!-- Copyright 2026 Stephan Schlöpke -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>StepH_GameEventScript_Tests</RootNamespace>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>StepH.GameEventScript.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/StepH.GameEventScript/StepH.GameEventScript.csproj" />
        <ProjectReference Include="../../src/StepH.GameEventScript.CSharpBridge/StepH.GameEventScript.CSharpBridge.csproj" />
        <ProjectReference Include="../../src/StepH.GameEventScript.Conformance/StepH.GameEventScript.Conformance.csproj" />
        <ProjectReference Include="../StepH.GameEventScript.Conformance.Worker/StepH.GameEventScript.Conformance.Worker.csproj" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
        <AssemblyMetadata Include="BuildSdkVersion" Value="$(NETCoreSdkVersion)" />
        <Compile Include="../StepH.GameEventScript.Conformance.Worker/WorkerProtocol.cs" Link="Conformance/WorkerProtocol.cs" />
    </ItemGroup>

</Project>
