<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>ges</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\s*module\s+[A-Za-z_][A-Za-z0-9_]*\b</string>
	<key>name</key>
	<string>GameEventScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#messages</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selectors</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#extensions-and-types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key-phrases</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:infinity|pi|e|tau)\b|[∞∏ℇτ]</string>
					<key>name</key>
					<string>constant.language.numeric.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#[a-z][A-Za-z]*(?:_[0-9]+)?\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.tag.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(module)\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.module.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.record.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(record)\s+(:[a-z][A-Za-z]*|[a-z][A-Za-z]*(?:_[0-9]+)?)\b</string>
					<key>name</key>
					<string>meta.record.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(function)\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.function.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.predicate.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(predicate)\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.predicate.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.handler.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.handler.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(on)\s+(@?[A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.handler.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.local.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(let)\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.variable.let.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>extensions-and-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:tag\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.tag.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.primitive.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.bracket.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.unit.gameeventscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.bracket.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(quantity)(\()((?:none|m|meter|s|second|degree|°))(\))(?=$|[^A-Za-z0-9_])</string>
					<key>name</key>
					<string>support.type.primitive.quantity.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!:)\b(?:numeric|integer|fractional)\b</string>
					<key>name</key>
					<string>support.type.primitive.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:distance|length)([ \t]+)(squared)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:angle)([ \t]+)(between)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:abs|ln|exp|sqrt|cbrt|chance|floor|ceil|truncate|rad|deg|sin|cos|tan|asin|acos|atan|atan2|hypot|distance|length|normalize|dot|cross)\b</string>
					<key>name</key>
					<string>support.function.prefix.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:wrap)([ \t]+)(degree)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:round)([ \t]+)(half)([ \t]+)(even|up|down)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(series)([ \t]+)(fibonacci|factorial)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?:text|boolean|number|percentage|vector|point|series|range|message|handler|list|map|dice)(?=$|[^A-Za-z0-9_])</string>
					<key>name</key>
					<string>support.type.primitive.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:[a-z][A-Za-z]*(?=$|[^A-Za-z0-9_])</string>
					<key>name</key>
					<string>entity.name.type.custom.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>key-phrases</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(roll)([ \t]+)(dice)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(random)([ \t]+)(with|from)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(clamp)(?=\s)</string>
					<key>name</key>
					<string>keyword.operator.word.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(min|max)([ \t]+)(of)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(has)([ \t]+)(value)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(in)([ \t]+)(values)([ \t]+)(of)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(starts)([ \t]+)(with)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(ends)([ \t]+)(with)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(not)([ \t]+)(empty|nothing|numeric|integer|fractional)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(empty|nothing|numeric|integer|fractional)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(not)([ \t]+)(at)([ \t]+)(least|most)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(at)([ \t]+)(least|most)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(not)([ \t]+)(less|more)([ \t]+)(than)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(is)([ \t]+)(less|more)([ \t]+)(than)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.word.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(or)([ \t]+)(less|more)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(clamped)([ \t]+)(between)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(computed)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(weighted)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(order)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(group)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(distinct)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(sort)([ \t]+)(ascending|descending)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(take|drop)([ \t]+)(first|last|highest|lowest)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(at)([ \t]+)(random)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(pair)([ \t]+)(of)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(three|four|five|six|seven)([ \t]+)(of)([ \t]+)(a)([ \t]+)(kind)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(full)([ \t]+)(house)\b</string>
					<key>name</key>
					<string>meta.keyword-phrase.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:if|else|for|in|from|to|when|otherwise|matching|without|with)\b</string>
					<key>name</key>
					<string>keyword.control.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:as|be|where|nothing)\b</string>
					<key>name</key>
					<string>keyword.other.definition.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:or|xor|and|not|is|empty|div|mod|rem|of)\b</string>
					<key>name</key>
					<string>keyword.operator.word.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:random|clamp|min|max|zip|default)\b</string>
					<key>name</key>
					<string>keyword.operator.word.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:emit|publish)\b</string>
					<key>name</key>
					<string>keyword.control.emit.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*(?=\s*:)</string>
					<key>name</key>
					<string>variable.parameter.label.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
					<key>name</key>
					<string>variable.other.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>_</string>
					<key>name</key>
					<string>variable.language.placeholder.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>messages</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.emit.gameeventscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.message.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(emit|publish)\s+([A-Z][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>meta.message.dispatch.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z][A-Za-z0-9_]*\b</string>
					<key>name</key>
					<string>entity.name.type.class.message.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d(?:[\d_]*\d)?d\d(?:[\d_]*\d)?\b</string>
					<key>name</key>
					<string>constant.numeric.dice.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d(?:[\d_]*\d)?(?:\.\d(?:[\d_]*\d)?)?%</string>
					<key>name</key>
					<string>constant.numeric.percentage.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d(?:[\d_]*\d)?(?:\.\d(?:[\d_]*\d)?)?(?:m|s|°)(?=$|[^A-Za-z0-9_])</string>
					<key>name</key>
					<string>constant.numeric.unit.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d(?:[\d_]*\d)?(?:\.\d(?:[\d_]*\d)?)?\b</string>
					<key>name</key>
					<string>constant.numeric.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=&gt;|-&gt;|[→⇒↦]</string>
					<key>name</key>
					<string>keyword.operator.arrow.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;|&lt;=|&gt;=|=|&lt;|&gt;|[≤≥≠]</string>
					<key>name</key>
					<string>keyword.operator.comparison.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[|&amp;]</string>
					<key>name</key>
					<string>keyword.operator.collection.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[!~¬∧∨⊕∈∉]</string>
					<key>name</key>
					<string>keyword.operator.logical.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[+\-−*/·×÷⋅^²³]</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[,;.]</string>
					<key>name</key>
					<string>punctuation.separator.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[(){}\[\]]</string>
					<key>name</key>
					<string>punctuation.bracket.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(take|drop)([ \t]+)(first|last|highest|lowest)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(sort)([ \t]+)(ascending|descending)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(order|group|distinct)([ \t]+)(by)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(choose|draw)([ \t]+)(at)([ \t]+)(random)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(has|take)([ \t]+)(full)([ \t]+)(house)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(has|take)([ \t]+)(three|four|five|six|seven)([ \t]+)(of)([ \t]+)(a)([ \t]+)(kind)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(has|take)([ \t]+)(pair)([ \t]+)(of)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector.pipeline.gameeventscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.definition.gameeventscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:(has|take)([ \t]+)(pair|straight)\b</string>
					<key>name</key>
					<string>meta.selector-phrase.gameeventscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?:any|all|filter|has|take|drop|count|choose|draw|shuffle|reverse|sum|average|select|contains|sort|first|last|single|min|max|highest|lowest|map|distinct|group|order|term|keys|values|entries)\b</string>
					<key>name</key>
					<string>support.function.selector.pipeline.gameeventscript</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.gameeventscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>constant.character.escape.quote.gameeventscript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.gameeventscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
							<key>name</key>
							<string>constant.character.escape.quote.gameeventscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gameeventscript</string>
</dict>
</plist>
